"""initial migration

Revision ID: 0391dc56f062
Revises: None
Create Date: 2019-08-05 14:55:06.826625

"""

# revision identifiers, used by Alembic.
revision = '0391dc56f062'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adminName', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weeklyBedtime', sa.String(length=16), nullable=True),
    sa.Column('weeklyFrequency', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=16), nullable=True),
    sa.Column('idealBedtime', sa.String(length=32), nullable=True),
    sa.Column('currentBedtime', sa.String(length=32), nullable=True),
    sa.Column('currentState', sa.String(length=32), nullable=True),
    sa.Column('weeklyPlanId', sa.Integer(), nullable=True),
    sa.Column('weeklyHit', sa.Integer(), nullable=True),
    sa.Column('weeklyMiss', sa.Integer(), nullable=True),
    sa.Column('userChoiceA', sa.String(length=32), nullable=True),
    sa.Column('userChoiceB', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['weeklyPlanId'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('isUser', sa.Boolean(), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('time', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('weeklyPlanId', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('isSlept', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weeklyPlanId'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('data')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('table')
    op.drop_table('plans')
    op.drop_table('admin')
    # ### end Alembic commands ###
